spring:
  datasource:
    url: jdbc:mysql://localhost:3306/authdb_dev
    username: root
    password: Test@12345
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
